config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :categories, except: %i[destroy update edit]
  resources :pictures, except: %i[index destroy create update edit] do
    post :upload, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pictures

  validates :name, presence: true, uniqueness: true
end

app/models/concerns/picture_concern.rb
module PictureConcern
  extend ActiveSupport::Concern

  included do
    self.table_name = 'pictures'
    after_create_commit :set_average_color
    after_create_commit { PictureRelayJob.perform_later(self) }

    has_one_attached :image
    belongs_to :category

    scope :newest, -> { order(created_at: :desc) }
    scope :in_category, ->(id) { where(category_id: id) }
    scope :with_category, -> { joins(:category) }
    scope :with_related, ->(id) { where(related_id: id) }

    validates :name, presence: true, uniqueness: true
    validates :image, attached: true, content_type: %i[png jpg jpeg]
  end

  def set_average_color
    image_content = image.download
    self.average_color = Averagecolor.new(image_content).perform
    save
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  include PictureConcern
end

app/models/related_picture.rb
class RelatedPicture < Picture
  include PictureConcern

  validate :validate_mime_type
  validates :image, ratio: :related

  private

  def validate_mime_type
    primary_image = Picture.find(related_id).image
    return if image.content_type == primary_image.content_type

    errors.add(:image, "Must be #{primary_image.content_type} content type")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.valid?
      redirect_to categories_path
    else
      flash[:error] = @category.errors.full_messages
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @pictures = Picture.in_category(@category.id).newest
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pictures = Picture.with_category.newest
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def upload
    picture, path = switch_model
    unless picture.valid? && picture.save
      flash[:error] = picture.errors.full_messages
    end
    redirect_to path
  end

  def show
    @picture = Picture.find(params[:id])
    @pictures = RelatedPicture.with_related(params[:id]).with_category.newest
  end

  private

  def switch_model
    if upload_params[:category_id].blank?
      assign_picture
    else
      assign_related_picture
    end
  end

  def assign_picture
    picture = Picture.new(upload_params)
    picture.category_id = params[:id]
    path = category_path(params[:id])
    [picture, path]
  end

  def assign_related_picture
    picture = RelatedPicture.new(upload_params)
    picture.related_id = params[:id]
    path = picture_path(params[:id])
    [picture, path]
  end

  def upload_params
    params.require(:picture).permit(:image, :name, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    hash = {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }
    hash.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(*)
    flash.each do |msg_type, messages|
      concat(
        content_tag(:div, messages, class: "alert #{bootstrap_class_for(msg_type)}", role: 'alert') do
          concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
          concat content_tag(
            :ul,
            messages.map do |m|
              content_tag(:li, m)
            end.join.html_safe,
            class: 'list-unstyled'
          )
        end
      )
    end
    nil
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/categories/index.html.erb
<div class="row py-1">
  <div class="col">
    <h2>Categories</h2>
  </div>
  <div class="col text-right">
    <%= link_to "Add category", new_category_path, :class => 'btn btn-outline-dark text-right' %>
  </div>
</div>

<div class="row">
  <%- @categories.each do |category| %>
    <div class="col-md-3">
      <div class="card mb-3" style="width: 16rem;">
        <div class="card-body">
          <h5 class="card-title"><%= category.name %></h5>
          <div class="d-flex justify-content-between align-items-center">
            <small><%= link_to "View", category_path(category), :class => 'card-link' %></small>
            <small class="text-muted">added: <i><%= category.created_at.strftime("%F %R") %></i></small>
          </div>
        </div>
      </div>
    </div>
  <%- end %>
</div>

app/views/categories/new.html.erb
<h2>New Category</h2>

<%= form_for @category, url: categories_path do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, autocomplete: 'name', value: @category.name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-outline-dark text-right' %>
  </div>

<% end %>

app/views/categories/show.html.erb
<h2>Category: <%= @category.name %></h2>

<%= render partial: "shared/upload_form" %>
<hr>
<%= render partial: "shared/list_pictures" %>

app/views/home/index.html.erb
<div class="row py-1">
  <div class="col">
    <h2>Latest uploads</h2>
  </div>
</div>
<%= render partial: "shared/list_pictures" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoGallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/header" %>
    <main role="main">
      <div class="py-3 bg-light">
        <div class="container">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pictures/show.html.erb
<h2>Picture: <%= @picture.name %></h2>
<hr>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="card mb-8 shadow-sm">
      <img class="card-img-top" src="<%= url_for(@picture.image.variant(resize_to_limit: [800, 800])) %>" alt="<%= @picture.name %>" >
      <div class="card-body">
        <div class="card-text row">
          <div class="col-md-6">
            <%= @picture.name %>
          </div>
          <div class="col-md-6">
            <div class="text-muted text-right">
              <small>Category: <%= @picture.category.name %> | Color: 
              <span class="color-box" style="background-color:<%= @picture.average_color %>"></span>
              </small>
            </div>
          </div>
        </div>
        <hr>
        <div class="d-flex justify-content-between align-items-center">
          <div class="upload">
            <h3>Upload related photo</h3>
            <%= render partial: "shared/upload_form" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-1"></div>
</div>
<hr>
<h3>Related photos</h3>
<%= render partial: "shared/list_pictures" %>

app/views/shared/_header.html.erb
<header>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Gallery</strong>
      </a>
      <nav class="nav">
        <%= link_to "Categories", categories_path, :class => 'nav-link text-white' %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_list_pictures.html.erb
<div class="row list-pictures">
  <% @pictures.each  do |picture| %>
    <%- @picture = picture %>
    <%= render partial: "shared/picture" %>
  <% end %>
</div>
        

app/views/shared/_picture.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm">
    <img src="<%= url_for(@picture.image.variant(resize_to_limit: [348, 348])) %>" alt="<%= @picture.name %>">
    <div class="card-body">
      <p class="card-text"><%= @picture.name %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "View", picture_path(@picture.id), :class => 'btn btn-sm btn-outline-secondary' if @picture.related_id.nil? %>
        </div>
        <small class="text-muted">Category: <%= @picture.category.name %> | Color: 
          <span class="color-box" style="background-color:<%= @picture.average_color %>"></span>
        </small>
      </div>
    </div>
  </div>
</div>

app/views/shared/_upload_form.html.erb
<%= form_for :picture, url: upload_picture_path do |f| %>

  <%= f.hidden_field :category_id, value: @picture.category_id unless @picture.nil? %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control', value: '' %>
  </div>

  <div class="form-group">
    <label for="formImage">Upload new photo</label>
    <%= f.file_field :image, class: 'form-control-file', id: 'formImage' %>
  </div>

  <div class="form-group">
    <%= f.submit "Upload", class: "btn btn-primary available-tables-btn", data: {disable_with: "Please wait..."} %>
  </div>

<% end %>